---
version: "3.8"
services:
  auth-service:
    build:
      context: ./backend/auth-service
    ports:
      - "8001:8000"
    environment:
      JWT_SECRET: supersecretkey
      JAEGER_HOST: jaeger
      JAEGER_PORT: 6831

  profiling-service:
    build:
      context: ./backend/profiling-service
    ports:
      - "8002:8000"
    environment:
      JWT_SECRET: supersecretkey
      JAEGER_HOST: jaeger
      JAEGER_PORT: 6831

  vismagi-service:
    build:
      context: ./backend/vismagi-service
    ports:
      - "8003:8000"
    environment:
      JAEGER_HOST: jaeger
      JAEGER_PORT: 6831

  optimization-service:
    build:
      context: ./backend/optimization-service
    ports:
      - "8004:8000"
    environment:
      JWT_SECRET: supersecretkey
      JAEGER_HOST: jaeger
      JAEGER_PORT: 6831

  simulation-service:
    build:
      context: ./backend/simulation-service
    ports:
      - "8005:8000"
    environment:
      JWT_SECRET: supersecretkey
      JAEGER_HOST: jaeger
      JAEGER_PORT: 6831

  pdf-service:
    build:
      context: ./backend/pdf-service
    ports:
      - "8006:8000"
    environment:
      JWT_SECRET: supersecretkey
      JAEGER_HOST: jaeger
      JAEGER_PORT: 6831

  reporting-service:
    build:
      context: ./backend/reporting-service
    ports:
      - "8007:8000"
    environment:
      JWT_SECRET: supersecretkey
      JAEGER_HOST: jaeger
      JAEGER_PORT: 6831
    depends_on:
      - optimization-service
      - vismagi-service
      - pdf-service

  gateway:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      JWT_SECRET: supersecretkey
      JAEGER_HOST: jaeger
      JAEGER_PORT: 6831
    depends_on:
      - auth-service
      - profiling-service
      - vismagi-service
      - optimization-service
      - simulation-service
      - pdf-service
      - reporting-service

  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - "16686:16686"
      - "6831:6831/udp"
