---
version: "3.8"
services:
  auth-service:
    build:
      context: ./backend/auth-service
    ports:
      - "8001:8000"
    environment:
      JWT_SECRET: supersecretkey

  profiling-service:
    build:
      context: ./backend/profiling-service
    ports:
      - "8002:8000"

  vismagi-service:
    build:
      context: ./backend/vismagi-service
    ports:
      - "8003:8000"

  optimization-service:
    build:
      context: ./backend/optimization-service
    ports:
      - "8004:8000"

  simulation-service:
    build:
      context: ./backend/simulation-service
    ports:
      - "8005:8000"

  pdf-service:
    build:
      context: ./backend/pdf-service
    ports:
      - "8006:8000"

  gateway:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      JWT_SECRET: supersecretkey
    depends_on:
      - auth-service
      - profiling-service
      - vismagi-service
      - optimization-service
      - simulation-service
      - pdf-service
